name       : python-distro
version    : 1.4.0
release    : 1
source     :
    -  https://pypi.python.org/packages/source/d/distro/distro-1.4.0.tar.gz : 362dde65d846d23baee4b5c058c8586f219b5a54be1cf5fc6ff55c4578392f57
license    : Apache-2.0
component  : programming.python
summary    : An OS platform information API
description: |
    Distro provides information about the OS distribution it runs on, such as a reliable machine-readable ID, or version information.
builddeps  :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3 -v
