name       : python-distro
version    : 1.8.0
release    : 8
source     :
    - https://pypi.python.org/packages/source/d/distro/distro-1.8.0.tar.gz : 02e111d1dc6a50abb8eed6bf31c3e48ed8b0830d1ea2a1b78c61765c2513fdd8
license    : Apache-2.0
component  : programming.python
summary    : An OS platform information API
description: |
    Distro provides information about the OS distribution it runs on, such as a reliable machine-readable ID, or version information.
builddeps  :
    - python-build
    - python-installer
    - python-pytest
    - python-wheel
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3 -v
