name       : python-distro
version    : 1.5.0
release    : 3
source     :
    - https://pypi.python.org/packages/source/d/distro/distro-1.5.0.tar.gz : 0e58756ae38fbd8fc3020d54badb8eae17c5b9dcbed388b17bb55b8a5928df92
license    : Apache-2.0
component  : programming.python
summary    : An OS platform information API
description: |
    Distro provides information about the OS distribution it runs on, such as a reliable machine-readable ID, or version information.
builddeps  :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3 -v
